name: A workflow for Creating File Leaderboard
on: push
jobs:
  build:
    name: File Leaderboard Action
    runs-on: ubuntu-latest
    steps:
      - name: Random Selector
        id: RandomSelector
        uses: "./"
        with:
            data: "1..100"
            returnCount: "5"
      