name: A workflow for Creating File Leaderboard
on: push
jobs:
  build:
    name: File Leaderboard Action
    runs-on: ubuntu-latest
    steps:
      - name: Random Selector Dictionary with Return Count
        id: RandomSelector
        uses: "./"
        with:
            data: "{1:1, 2:2, 3:3, 4:4, 5:5}"
            returnCount: "3"
      