name: A workflow for Creating File Leaderboard
on: push
jobs:
  build:
    name: File Leaderboard Action
    runs-on: ubuntu-latest
    steps:
      - name: Random Selector with No Return Count
        id: RandomSelector
        uses: "./"
        with:
            data: "[1, 2, 3, 4, 5]"
            
      