name: A workflow for test Random Selector
on: push
jobs:
  build:
    name: Random Selector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v1
        
      - name: Random Selector
        id: RandomSelector1
        uses: "./"
        with:
            data: "[1, 2, 3, 4, 5]"
            returnCount: "2"
      
      - name: Random Selector Dictionary with Return Count
        id: RandomSelector2
        uses: "./"
        with:
            data: "{1:1, 2:2, 3:3, 4:4, 5:5}"
            returnCount: "3"
      
      - name: Random Selector with No Return Count
        id: RandomSelector3
        uses: "./"
        with:
            data: "[1, 2, 3, 4, 5]"
      
      - name: Random Selector with No Return Count
        id: RandomSelector4
        uses: "./"
        with:
            data: "{1:1, 2:2, 3:3, 4:4, 5:5}"
      
      - name: Random Selector with No Return Count
        id: RandomSelector5
        uses: "./"
        with:
            data: "{'1':'1', '2':'2', '3':3, '4':4, '5':5}"
      
      - name: Random Selector
        id: RandomSelector6
        uses: "./"
        with:
            data: "1..100"
            returnCount: "5"
            
      - name: Random Selector
        id: RandomSelector7
        uses: "./"
        with:
            data: "[1, 2, 3, 4, 5"
            returnCount: "2"